In [5]:
import numpy as np

In [6]:
#iniciando numpy
valoraciones = np.array([[1,2,4,5], [6,3,7,1], [0,9,8,7]])
valoraciones

array([[1, 2, 4, 5],
       [6, 3, 7, 1],
       [0, 9, 8, 7]])

In [9]:
#accediendo a la informacion del array 2 maneras.

valoraciones[0][1]
valoraciones[0,1]

np.int64(2)

In [26]:
#creando un array con mas dimensiones

valoraciones2 = np.ones((3,2,4))

In [27]:
valoraciones2

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [19]:
valoraciones2[0,1,2]

np.int64(4)

In [20]:
np.zeros([3,2,4])

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [29]:
#sumando los valores de arrays
valoraciones2 + np.ones((3,2,4))

array([[[2., 2., 2., 2.],
        [2., 2., 2., 2.]],

       [[2., 2., 2., 2.],
        [2., 2., 2., 2.]],

       [[2., 2., 2., 2.],
        [2., 2., 2., 2.]]])

In [30]:
valoraciones2

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [31]:
np.mean(valoraciones2)

np.float64(1.0)

In [35]:
np.mean(valoraciones2, axis = 2)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [36]:
#convirtiendo valores en dimisiones indicadas
np.reshape([1,2,3,4,5,6,7,8,9,10,11,12], (3,2,2))

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [ ]:
#ejecutando mediana en data frame cargado
np.median(df["columna1"])

In [37]:
#generando elementos aleatorios
np.random.rand(2,2)

array([[0.94874849, 0.56227968],
       [0.37390057, 0.00355997]])